apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4499
      nodePort: 31493  # Specify a node port (use any available port number)
  type: NodePort  # Use NodePort type for local development


